Stuck on an error
After wrestling with a couple of different vexing issues I'm now stuck on this one:
ValueError: invalid literal for int() with base 10: b'1.0'

This is more concerning because I'm pretty sure I didn't change anything that caused this.